language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - cd pybotics/ut
  - coverage run --source=pybotics run_tests.py

after_success: coveralls
