language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.5-dev"
    - python: "3.6"
    - python: "3.6-dev" 
    - python: "3.7-dev"
    - python: "nightly"
  fast_finish: true
  allow_failures:
    - python: "2.7"
    - python: "3.4"
    - python: "3.7-dev"
    - python: "nightly"

# command to install dependencies
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - find .
  
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - pip install pytest-cov
  - pip install pydocstyle
  - pip install flake8
  - pip install vulture
  - pip install bandit

# command to run tests
script:
  - python setup.py test

after_success:
  - coveralls
  - codecov
  - pydocstyle pybotics
  - flake8 --show-source pybotics
  - vulture .
  - bandit -r pybotics

# notification settings
notifications:
  email: false
  
