language: python

matrix:
  include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.5-dev"
    - python: "3.6"
    - python: "3.6-dev" 
    - python: "3.7-dev"
    - python: "nightly"
  fast_finish: true
  allow_failures:
    - python: "3.7-dev"
    - python: "nightly"

# command to install dependencies
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - pip install pytest-cov
  - pip install pydocstyle
  - pip install bandit

# command to run tests
script:
  - python setup.py test

after_success:
  - coveralls
  - codecov
  - pydocstyle pybotics
  - bandit -r pybotics

# notification settings
notifications:
  email: false
  
