environment:
  matrix:
  - PYTHON: "C:\\Python34"
  - PYTHON: "C:\\Python35"
  - PYTHON: "C:\\Python34-x64"
    DISTUTILS_USE_SDK: "1"
  - PYTHON: "C:\\Python35-x64"
  - PYTHON: "C:\\Python36-x64"

install:
- "%PYTHON%\\python.exe -m pip install -r requirements\\appveyor.txt"
- "%PYTHON%\\python.exe -m pip install -r requirements\\main.txt"
- "%PYTHON%\\python.exe -m pip install -r requirements\\unit-testing.txt"
- "%PYTHON%\\python.exe -m pip install -r requirements\\versioning.txt"
- "%PYTHON%\\python.exe utilities\\write_version.py"
- "%PYTHON%\\python.exe -m pip install -e ."

# disable automatic builds
build: off

test_script:
- "%PYTHON%\\python.exe -m pytest tests"

