version: 2

jobs:
  build:
    docker:
    - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
    - checkout

    - run:
        name: install
        command: |
          python3 -m venv venv
          . venv/bin/activate
          python -V
          python setup.py install
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

    - run:
        name: test
        command: |
          . venv/bin/activate
          pip list
          python setup.py test
