version: 2

jobs:
  linux:
    docker:
    - image: circleci/python:3
    steps:
    - checkout
    - run:
        name: install
        command: |
          python -m venv venv
          . venv/bin/activate
          python -V
          pip install -q -r requirements.txt
          pip install -q -r dev-requirements.txt
          python setup.py install
    - run:
        name: test
        command: |
          . venv/bin/activate
          python -V
          python setup.py test

  osx:
    macos:
      xcode: '9.2.0'
    steps:
    - checkout
    - run:
        name: install
        command: |
          brew upgrade python
          python3 -V
          python3 -m venv venv
          . venv/bin/activate
          python -V
          pip install -q -r requirements.txt
          pip install -q -r dev-requirements.txt
          python setup.py install
    - run:
        name: test
        command: |
          python3 -V
          . venv/bin/activate
          python -V
          python setup.py test

workflows:
  version: 2
  test:
    jobs:
    - linux
    - osx
